spring:
  datasource:
    url: jdbc:mysql://localhost:3306/oauth2-jwt-testing
    username: root
    password: passord
    driver-class-name: com.mysql.cj.jdbc.Driver
  logging:
    level:
      org.springframework.security: trace

jwt:
  rsa-private-key: classpath:certificates/privateKey.pem
  rsa-public-key: classpath:certificates/publicKey.pem