spring:
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        password: passord
        url: jdbc:mysql://localhost:3306/quizopiadb
        username: root
    logging:
        level:
            org:
                springframework:
                    security: trace
    flyway:
        locations: classpath:db/migration
        enabled: true
        validate-on-migrate: true
        baseline-on-migrate: true
        baselineVersion: 1

jwt:
    rsa-private-key: classpath:certificates/privateKey.pem
    rsa-public-key: classpath:certificates/publicKey.pem