spring:
  mysql:
    console:
      enabled: true
    datasource:
      url: jdbc:mysql://localhost:3306/oath2-jwt-testing
      username: root
      password: passord
      driverClassName: com.mysql.cj.jdbc.Driver
    logging:
      level:
        org.springframework.security: trace