name: Continuous Integration and E2E Pipeline

on:
  push:
    branches:
      - '*'  # Trigger on push to any branch
  pull_request:
    branches:
      - main  # Trigger on pull requests to main

jobs:
  build-and-test-backend:
    runs-on: ubuntu-latest
    
    services:
      mysql-service:
        image: mysql:8.0.36
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: QuizopiaDB_Test
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h localhost -ppassword" 
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5
    
    steps:
      - name: Checkout Repository Code
        uses: actions/checkout@v4

      - name: Setup JDK 17 for Java Build
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build and Run Tests with Maven
        run: mvn -B -Dspring.profiles.active=test package --file pom.xml
        env:
          SPRING_DATASOURCE_URL: jdbc:mysql://localhost:3306/QuizopiaDB_Test?allowPublicKeyRetrieval=true&useSSL=false
          SPRING_DATASOURCE_USERNAME: root
          SPRING_DATASOURCE_PASSWORD: password

  trigger-frontend-e2e:
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    runs-on: ubuntu-latest
    needs: build-and-test-backend
    steps:
      - name: Trigger E2E Tests
        uses: benc-uk/workflow-dispatch@v1.1
        with:
          workflow: "E2E Tests"
          token: ${{ secrets.YOUR_ACTION }}
          repo: heikkkk/IDATT2105-Semester-Project-Frontend
          ref: main
          inputs: '{"PIPELINE_TYPE":"multi-project-pipeline"}'
